# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
