# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20171129_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='ip',
        ),
        migrations.AddField(
            model_name='reviews',
            name='ip_address',
            field=models.CharField(default='ABC', max_length=120),
        ),
    ]
