# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20171205_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ip_address',
            field=models.CharField(default='ABC', max_length=120, null=True),
        ),
    ]
