# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 14:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20171205_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', protocol='IPv4', verbose_name='Last Login IP'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
